### ISSUE TITLE
Question: Browserify and library

### ISSUE THREAD

**Issue by MichaelXavier** [bodil/pulp#12]
Hi,

I've been using the pulp browserify to build my project. I've been using dummy data for a main, but in reality, my project's entry point is a single function that takes a configuration.  Is there any way to get the DCE and bundling functionality of browserify here with the ability to specify a your library entry points rather than just main?  It makes sense that I should need to specify the API surface area or DCE can't do its job, but I need the user in jsland to build a config and pass it in rather than the code running as soon as it is loaded with no input. Any suggestions?

**Comment by bodil** [comment]
Essentially, you'd like an option for not adding in the entry point code in the browserify process, leaving the user to invoke it manually? Should be a simple matter of a command line flag, if I understand you correctly.
