### ISSUE TITLE
/usr/bin/pulp has DOS style line endings

### ISSUE THREAD

**Issue by fgc** [bodil/pulp#2]
I installed pulp from npm in Ubuntu 14 and /usr/bin/pulp refused to run with some "file not found" nonsense.

Turns out that the file has CR-LF line endings and those manage to confuse the shebang at the top into trying to run the inexistent "node^M" interpreter.

**Comment by michaelficarra** [comment]
It seems these line endings are only there in the npm release, not in the files in the repo. @bodil can you run `dos2unix` on your local copies of the files (or just clone again) and make a patch release?

**Comment by bodil** [comment]
omg Windows, seriously?

Yeah, the 1.1.2 release was about making it run on Windows without too much pain, so once I'd verified it worked, I just ran npm publish from my Windows box. Should have known better than to ever trust Windows to do anything right. :(
